/**
 * Uploading a PDF.
 *
 * The byte extractor can only read a PDF whose text is stored as plain
 * text-showing operators, which most real ones are not — so a PDF upload used
 * to end in "no readable text was found". It is now read by the model instead.
 *
 * What has to hold: the request carries the PDF in the shape the API defines,
 * the transcript becomes knowledge, and every way it can go wrong is said out
 * loud rather than swallowed — a half-read document that looks fully indexed
 * is the failure that matters here.
 */

import test from 'node:test';
import assert from 'node:assert/strict';

import worker from '../src/index.js';
import { createStorage } from '../src/storage.js';
import { loadConfig } from '../src/config.js';
import { retrieve } from '../src/retrieve.js';
import { ingest } from '../src/ingest.js';
import { toBase64, estimatePages, splitSections } from '../src/pdfText.js';
import { fakeKV } from './helpers.js';

const ENV = {
  AUTH_MODE: 'dev',
  ALLOW_DEV_AUTH: 'true',
  BOOTSTRAP_ADMINS: 'boss@vikat.ai',
  ALLOWED_EMAIL_DOMAINS: 'vikat.ai',
  ANTHROPIC_API_KEY: 'sk-test',
  SHAREPOINT_SITE_ID: 'host,site,web',
  SHAREPOINT_LIBRARY: 'Documents',
  SHAREPOINT_GENERATED_FOLDER: 'Generated by assistant',
  GRAPH_TENANT_ID: 't',
  GRAPH_CLIENT_ID: 'c',
  GRAPH_CLIENT_SECRET: 's',
};

function setup(extra = {}) {
  const kv = fakeKV();
  const env = { ...ENV, ...extra, VIKAT_KV: kv };
  return { env, cfg: loadConfig(env), storage: createStorage(env, loadConfig(env)) };
}

const TRANSCRIPT =
  '## Harvest window risk\n\n' +
  'Agricultural operations concentrate risk into a few weeks a year, and severity scoring has never known that. ' +
  'A medium CVE in March and the same CVE in October are not the same problem for a grower.\n\n' +
  '## Deployment\n\n' +
  'Vikat deploys as SaaS or self-hosted, and the self-hosted form keeps every packet inside the customer estate ' +
  'so a regulated grower never has to argue about data residency with their auditor.';

/** A PDF the BYTE extractor can read, for the fallback cases. */
const READABLE_PDF = new TextEncoder().encode(
  '%PDF-1.4\nstream\nBT /F1 12 Tf (Vikat deploys as SaaS or self-hosted, and the self-hosted form keeps ' +
    'every packet inside the customer estate for a regulated grower.) Tj ET\nendstream\n%%EOF',
);

/** A PDF nothing can read without looking at the pixels — a scan, in effect. */
const SCANNED_PDF = new TextEncoder().encode('%PDF-1.4\nstream\n \nendstream\n%%EOF');

/** One SSE stream of a finished message, as the SDK expects to read it. */
function sse(events) {
  const body = events.map((e) => `event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`).join('');
  return new Response(body, { status: 200, headers: { 'content-type': 'text/event-stream' } });
}

function anthropicReply(text, { stopReason = 'end_turn' } = {}) {
  return sse([
    {
      type: 'message_start',
      message: {
        id: 'msg_1', type: 'message', role: 'assistant', model: 'm',
        content: [], stop_reason: null, stop_sequence: null,
        usage: { input_tokens: 4321, output_tokens: 0 },
      },
    },
    { type: 'content_block_start', index: 0, content_block: { type: 'text', text: '' } },
    { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text } },
    { type: 'content_block_stop', index: 0 },
    { type: 'message_delta', delta: { stop_reason: stopReason, stop_sequence: null }, usage: { output_tokens: 210 } },
    { type: 'message_stop' },
  ]);
}

/**
 * One stub for both services the upload path talks to.
 *
 * They share globalThis.fetch, so routing them apart here is what lets a test
 * assert on the Anthropic request body and the Graph upload in one run.
 */
function stubs({ anthropic = () => anthropicReply(TRANSCRIPT), uploadOk = true } = {}) {
  const calls = { anthropic: [], graph: [] };

  const fn = async (url, init) => {
    const u = String(url);

    if (u.includes('api.anthropic.com')) {
      calls.anthropic.push({ url: u, body: JSON.parse(init.body) });
      return anthropic();
    }

    calls.graph.push({ url: u, method: init?.method || 'GET' });
    if (u.includes('login.microsoftonline.com')) {
      return { ok: true, status: 200, json: async () => ({ access_token: 'tok', expires_in: 3600 }) };
    }
    if (u.endsWith('/drives')) {
      return {
        ok: true, status: 200,
        json: async () => ({ value: [{ id: 'd1', name: 'Documents', driveType: 'documentLibrary' }] }),
      };
    }
    if (!uploadOk) return { ok: false, status: 403, text: async () => 'denied' };
    return {
      ok: true, status: 201,
      json: async () => ({ webUrl: 'https://vikatai.sharepoint.com/sites/GTM/Brief.pdf', name: 'Brief.pdf' }),
    };
  };

  fn.calls = calls;
  return fn;
}

async function withFetch(stub, fn) {
  const original = globalThis.fetch;
  globalThis.fetch = stub;
  try {
    return await fn();
  } finally {
    globalThis.fetch = original;
  }
}

function upload(env, { name = 'Brief.pdf', bytes = READABLE_PDF, folder = 'Briefs' } = {}) {
  const form = new FormData();
  form.append('file', new File([bytes], name));
  form.append('library', 'Documents');
  form.append('folder', folder);

  return worker.fetch(
    new Request('https://x.test/admin/upload', {
      method: 'POST',
      headers: { 'X-Dev-User': 'boss@vikat.ai' },
      body: form,
    }),
    env,
    { waitUntil() {} },
  );
}

// --- the request the API actually receives --------------------------------

test('the PDF is sent as a document block, ahead of the instruction', async () => {
  const { env } = setup();
  const stub = stubs();
  await withFetch(stub, () => upload(env));

  assert.equal(stub.calls.anthropic.length, 1, 'the model should have been asked to read it');
  const content = stub.calls.anthropic[0].body.messages[0].content;

  assert.equal(content[0].type, 'document', 'the document comes first; the API defines it that way');
  assert.equal(content[0].source.type, 'base64');
  assert.equal(content[0].source.media_type, 'application/pdf');
  assert.equal(content[1].type, 'text');

  // A wrapped payload is rejected by the API, and the failure looks like a
  // corrupt file rather than a formatting mistake.
  assert.ok(!/[\r\n]/.test(content[0].source.data), 'base64 must carry no newlines');
  assert.equal(atob(content[0].source.data.slice(0, 8)).slice(0, 5), '%PDF-');
});

test('reading a PDF does not spend the output budget on thinking', async () => {
  // Thinking is drawn from max_tokens before any visible text. On a long
  // transcript that is budget taken straight out of the document.
  const { env } = setup();
  const stub = stubs();
  await withFetch(stub, () => upload(env));

  assert.equal(stub.calls.anthropic[0].body.thinking, undefined);
  assert.equal(stub.calls.anthropic[0].body.stream, true, 'a long read must not race the HTTP timeout');
});

test('a transcript gets its own, larger ceiling than a chat answer', async () => {
  // A faithful transcript of a long brief is tens of thousands of tokens. At
  // the chat ceiling it stops half-read.
  const { env, cfg } = setup();
  const stub = stubs();
  await withFetch(stub, () => upload(env));

  assert.equal(stub.calls.anthropic[0].body.max_tokens, cfg.PDF_READ_MAX_TOKENS);
  assert.ok(cfg.PDF_READ_MAX_TOKENS > cfg.MAX_TOKENS);
});

// --- the point of it all --------------------------------------------------

test('a PDF the byte extractor cannot read is still answerable after upload', async () => {
  const { env, storage } = setup();
  const res = await withFetch(stubs(), () => upload(env, { bytes: SCANNED_PDF }));
  const body = await res.json();

  assert.equal(res.status, 200, JSON.stringify(body));
  assert.equal(body.reader, 'model');
  assert.ok(body.chunks > 0);

  const block = await retrieve('harvest window severity scoring grower', { storage });
  assert.match(block, /harvest window/i, 'the transcript has to reach retrieval');
});

test('the transcript keeps the headings the document used', async () => {
  const { env, storage } = setup();
  await withFetch(stubs(), () => upload(env));

  const sections = (await storage.listKnowledge()).map((e) => e.section);
  assert.ok(sections.some((s) => /Harvest window risk/.test(s)), sections.join(' | '));
  assert.ok(sections.some((s) => /Deployment/.test(s)), 'both sections, not one blob');
});

test('what the read cost comes back with the result', async () => {
  const { env } = setup();
  const body = await (await withFetch(stubs(), () => upload(env))).json();

  assert.equal(body.usage.inputTokens, 4321);
  assert.equal(body.usage.outputTokens, 210);
});

// --- every way it goes wrong is said out loud -----------------------------

test('a transcript cut off at max_tokens warns that the document is half-read', async () => {
  const { env } = setup();
  const res = await withFetch(
    stubs({ anthropic: () => anthropicReply(TRANSCRIPT, { stopReason: 'max_tokens' }) }),
    () => upload(env),
  );
  const body = await res.json();

  assert.equal(res.status, 200);
  assert.ok(
    body.warnings.some((w) => /only the first part/i.test(w)),
    `a silently truncated document is the failure that matters: ${JSON.stringify(body.warnings)}`,
  );
});

test('the model being unreachable falls back to the byte extractor, and says so', async () => {
  const { env, storage } = setup();
  const res = await withFetch(
    stubs({ anthropic: () => { throw new Error('connection refused'); } }),
    () => upload(env),
  );
  const body = await res.json();

  assert.equal(res.status, 200, JSON.stringify(body));
  assert.equal(body.reader, 'bytes');
  assert.ok(body.warnings.some((w) => /falling back/i.test(w)), JSON.stringify(body.warnings));

  const block = await retrieve('self-hosted packet customer estate grower', { storage });
  assert.match(block, /self-hosted/i, 'a readable PDF still gets in without the model');
});

test('a scanned PDF the model cannot read either is refused, and never filed', async () => {
  const { env } = setup();
  const stub = stubs({ anthropic: () => { throw new Error('connection refused'); } });
  const res = await withFetch(stub, () => upload(env, { bytes: SCANNED_PDF }));

  assert.equal(res.status, 422);
  assert.equal(
    stub.calls.graph.filter((c) => c.method === 'PUT').length,
    0,
    'nothing unreadable may reach SharePoint looking indexed',
  );
});

test('a PDF past the page limit is refused before a single token is spent', async () => {
  const { env } = setup();
  const long = new TextEncoder().encode('%PDF-1.4\n' + '/Type /Page \n'.repeat(400) + '%%EOF');
  const stub = stubs();
  const res = await withFetch(stub, () => upload(env, { bytes: long }));

  assert.equal(res.status, 422);
  assert.equal(stub.calls.anthropic.length, 0, 'refusing after paying is not refusing');
  assert.match((await res.json()).warnings.join(' '), /pages/);
});

// --- the switch, and everything that is not a PDF -------------------------

test('PDF_READER=bytes never calls the model', async () => {
  const { env } = setup({ PDF_READER: 'bytes' });
  const stub = stubs();
  const res = await withFetch(stub, () => upload(env));

  assert.equal(res.status, 200);
  assert.equal(stub.calls.anthropic.length, 0);
  assert.equal((await res.json()).reader, 'bytes');
});

test('with no API key the model is not attempted, which is what CI is', async () => {
  const { env, cfg } = setup();
  delete env.ANTHROPIC_API_KEY;
  const stub = stubs();

  const read = await withFetch(stub, () => ingest(READABLE_PDF, 'Brief.pdf', { env, cfg }));

  assert.equal(read.ok, true);
  assert.equal(read.reader, 'bytes');
  assert.equal(stub.calls.anthropic.length, 0);
});

test('a .docx is read locally and costs nothing', async () => {
  const { env, cfg } = setup();
  const { zipSync, strToU8 } = await import('fflate');
  const docx = zipSync({
    'word/document.xml': strToU8(
      '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' +
        '<w:p><w:r><w:t>Vikat deploys as SaaS or self-hosted, and the self-hosted form keeps every packet ' +
        'inside the customer estate.</w:t></w:r></w:p></w:body></w:document>',
    ),
  });

  const stub = stubs();
  const read = await withFetch(stub, () => ingest(docx, 'Brief.docx', { env, cfg }));

  assert.equal(read.ok, true);
  assert.equal(stub.calls.anthropic.length, 0, 'only PDFs go to the model');
});

// --- the pieces -----------------------------------------------------------

test('base64 of a long file carries no newlines', () => {
  const big = new Uint8Array(200000).fill(0x41);
  const encoded = toBase64(big);
  assert.ok(!/[\r\n]/.test(encoded));
  assert.equal(atob(encoded).length, big.length, 'and it round-trips');
});

test('pages are counted off the page tree', () => {
  assert.equal(estimatePages(new TextEncoder().encode('/Type /Page \n/Type /Page \n')), 2);
  // /Pages is the tree node, not a page — counting it would inflate every file.
  assert.equal(estimatePages(new TextEncoder().encode('/Type /Pages\n/Count 9\n')), 9);
});

test('markdown before the first heading is not dropped', () => {
  // A model that opens with a sentence and only then writes "##" would
  // otherwise lose that sentence silently.
  const sections = splitSections('An opening line.\n\n## Later\nBody.', 'Brief.pdf');
  assert.equal(sections.length, 2);
  assert.equal(sections[0].title, 'Brief.pdf');
  assert.match(sections[0].content, /opening line/);
});
