/**
 * Uploading a document from the admin panel.
 *
 * Three things have to hold together: the assistant knows the document
 * immediately, the file reaches SharePoint where the collateral lives, and
 * once the nightly sync indexes it from there the document does not exist
 * twice.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { zipSync, strToU8 } from 'fflate';

import worker from '../src/index.js';
import { createStorage } from '../src/storage.js';
import { loadConfig } from '../src/config.js';
import { retrieve } from '../src/retrieve.js';
import { fakeKV } from './helpers.js';

const ENV = {
  AUTH_MODE: 'dev',
  ALLOW_DEV_AUTH: 'true',
  BOOTSTRAP_ADMINS: 'boss@vikat.ai',
  ALLOWED_EMAIL_DOMAINS: 'vikat.ai',
  ANTHROPIC_API_KEY: 'unused',
  SHAREPOINT_HOSTNAME: 'vikatai.sharepoint.com',
  SHAREPOINT_SITE_PATH: '/sites/VikatGTM',
  SHAREPOINT_SITE_ID: 'host,site,web',
  SHAREPOINT_LIBRARY: 'Documents',
  SHAREPOINT_GENERATED_FOLDER: 'Generated by assistant',
  GRAPH_TENANT_ID: 't',
  GRAPH_CLIENT_ID: 'c',
  GRAPH_CLIENT_SECRET: 's',
};

function setup() {
  const kv = fakeKV();
  const env = { ...ENV, VIKAT_KV: kv };
  return { env, storage: createStorage(env, loadConfig(env)) };
}

/** A .docx carrying one paragraph, which is all the extractor needs. */
function docxWith(text) {
  const doc =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' +
    `<w:p><w:r><w:t>${text}</w:t></w:r></w:p>` +
    '</w:body></w:document>';
  return zipSync({ 'word/document.xml': strToU8(doc) });
}

/** Graph, stubbed: a token, the drives, then the upload. */
function graphStub({ uploadOk = true } = {}) {
  const calls = [];
  const fn = async (url, init) => {
    const u = String(url);
    calls.push({ url: u, method: init?.method || 'GET' });

    if (u.includes('login.microsoftonline.com')) {
      return { ok: true, status: 200, json: async () => ({ access_token: 'tok', expires_in: 3600 }) };
    }
    if (u.endsWith('/drives')) {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          value: [
            { id: 'd1', name: 'Documents', driveType: 'documentLibrary' },
            { id: 'd2', name: 'CISO', driveType: 'documentLibrary' },
          ],
        }),
      };
    }
    if (!uploadOk) return { ok: false, status: 403, text: async () => 'denied' };
    return {
      ok: true,
      status: 201,
      json: async () => ({
        webUrl: 'https://vikatai.sharepoint.com/sites/VikatGTM/CISO/Brief.docx',
        name: 'Brief.docx',
      }),
    };
  };
  fn.calls = calls;
  return fn;
}

async function withFetch(stub, fn) {
  const original = globalThis.fetch;
  globalThis.fetch = stub;
  try {
    return await fn();
  } finally {
    globalThis.fetch = original;
  }
}

function upload(env, { name = 'Brief.docx', bytes, library = 'CISO', folder = 'CISO Briefs' } = {}) {
  const form = new FormData();
  form.append('file', new File([bytes || docxWith(LONG_TEXT)], name));
  form.append('library', library);
  form.append('folder', folder);

  return worker.fetch(
    new Request('https://x.test/admin/upload', {
      method: 'POST',
      headers: { 'X-Dev-User': 'boss@vikat.ai' },
      body: form,
    }),
    env,
    { waitUntil() {} },
  );
}

const LONG_TEXT =
  'Agricultural operations concentrate risk into a few weeks a year, and severity scoring has never known that. ' +
  'A medium CVE in March and the same CVE in October are not the same problem, because only one of them lands ' +
  'in the harvest window when the line cannot stop.';

// --- the assistant knows it immediately -----------------------------------

test('an uploaded document is answerable before any sync runs', async () => {
  const { env, storage } = setup();
  const res = await withFetch(graphStub(), () => upload(env));
  const body = await res.json();

  assert.equal(res.status, 200, JSON.stringify(body));
  assert.ok(body.chunks > 0, 'the text became knowledge');
  assert.equal(body.filed, true);

  const block = await retrieve('harvest window severity scoring', { storage });
  assert.match(block, /harvest window/i, 'retrieve must serve it on the next message');
});

test('a file whose text cannot be read is refused, and never filed', async () => {
  // A scanned PDF uploads cleanly and teaches the assistant nothing. Filing it
  // anyway would leave it in SharePoint looking indexed.
  //
  // The model reader is unreachable here (graphStub answers nothing else), so
  // this is the case where BOTH readers fail — and the message the admin gets
  // has to be about their document, not about the API. test/pdf.test.js
  // covers the model reader itself.
  const { env } = setup();
  const stub = graphStub();
  const res = await withFetch(stub, () =>
    upload(env, { name: 'scan.pdf', bytes: new Uint8Array([0x25, 0x50, 0x44, 0x46, 0x2d, 0x31, 0x2e, 0x34]) }),
  );

  assert.equal(res.status, 422);
  assert.match((await res.json()).error, /text/i);
  assert.equal(
    stub.calls.filter((c) => c.method === 'PUT').length,
    0,
    'nothing unreadable may reach SharePoint',
  );
});

test('an unsupported extension is refused by name', async () => {
  const { env } = setup();
  const res = await withFetch(graphStub(), () => upload(env, { name: 'notes.pages', bytes: new Uint8Array([1, 2, 3]) }));
  assert.equal(res.status, 400);
  assert.match((await res.json()).error, /\.pptx/);
});

// --- it reaches SharePoint, in the right place ----------------------------

test('the file is filed in the library and folder that were chosen', async () => {
  const { env } = setup();
  const stub = graphStub();
  await withFetch(stub, () => upload(env, { library: 'CISO', folder: 'CISO Briefs' }));

  const put = stub.calls.find((c) => c.method === 'PUT');
  assert.ok(put, 'the file should have been uploaded');
  assert.match(put.url, /\/drives\/d2\//, 'into the CISO drive, not the default one');
  assert.match(put.url, /CISO%20Briefs\/Brief\.docx/, 'and into the folder given');
});

test('the generated-documents folder is refused as a destination', async () => {
  // It is the one folder the sync skips unconditionally, so filing curated
  // collateral there would put it where nothing reads it — the mirror image of
  // the hazard that folder exists to prevent.
  const { env } = setup();
  const res = await withFetch(graphStub(), () => upload(env, { folder: 'Generated by assistant' }));
  const body = await res.json();

  assert.equal(res.status, 200, 'the knowledge is still saved');
  assert.equal(body.filed, false);
  assert.match(body.note, /NOT filed/);
});

test('Graph being down costs the filing, not the knowledge', async () => {
  const { env, storage } = setup();
  const res = await withFetch(graphStub({ uploadOk: false }), () => upload(env));
  const body = await res.json();

  assert.equal(res.status, 200);
  assert.ok(body.chunks > 0, 'the reason the admin uploaded it still happened');
  assert.equal(body.filed, false);
  assert.match(body.note, /NOT filed in SharePoint/);

  const block = await retrieve('harvest window', { storage });
  assert.match(block, /harvest/i);
});

// --- Collateral, and not twice --------------------------------------------

test('an uploaded document appears in Collateral straight away', async () => {
  const { env } = setup();
  await withFetch(graphStub(), () => upload(env));

  const res = await worker.fetch(
    new Request('https://x.test/collateral', { headers: { 'X-Dev-User': 'boss@vikat.ai' } }),
    env,
    { waitUntil() {} },
  );
  const { documents } = await res.json();

  const mine = documents.find((d) => d.name === 'Brief.docx');
  assert.ok(mine, 'the tab that lists what we have must list it');
  assert.match(mine.webUrl, /^https:\/\//);
});

test('one document, one row, however many passages it became', async () => {
  const { env, storage } = setup();
  await withFetch(graphStub(), () => upload(env));

  const entries = await storage.listKnowledge();
  const uploaded = await storage.listUploadedDocuments();

  assert.ok(entries.length >= 1);
  assert.equal(uploaded.length, 1, `${entries.length} passage(s) must still be one document`);
});

test('a superseded upload retires rather than being answered twice', async () => {
  // The night after an upload, the sync indexes the same file from SharePoint
  // and it lands in the compiled base. The provisional copy has to step aside,
  // or the assistant holds two of everything anyone ever uploaded.
  //
  // Tested against a page the compiled base ALREADY carries, because
  // retrieve() reads that set once at module load — pushing a page in later
  // would assert nothing.
  const { KNOWLEDGE } = await import('../src/knowledge.js');
  const compiledPage = KNOWLEDGE[0].page;

  const { storage } = setup();

  await storage.saveKnowledge(
    {
      section: 'Superseded.docx — body',
      content: 'Harvest windows concentrate risk into a few weeks, and severity scoring has never known that.',
      status: 'approved',
      sourcePath: compiledPage,
      uploadName: 'Superseded.docx',
      uploadWebUrl: 'https://vikatai.sharepoint.com/x/Superseded.docx',
    },
    'boss@vikat.ai',
  );
  await storage.saveKnowledge(
    {
      section: 'StillProvisional.docx — body',
      content: 'A medium CVE in March and the same CVE in October are not the same problem for a grower.',
      status: 'approved',
      sourcePath: 'sharepoint/CISO/Not yet synced.docx',
      uploadName: 'StillProvisional.docx',
      uploadWebUrl: 'https://vikatai.sharepoint.com/x/StillProvisional.docx',
    },
    'boss@vikat.ai',
  );

  const block = await retrieve('harvest severity CVE March October grower', { storage });

  assert.ok(
    !block.includes('Superseded.docx'),
    'an upload the compiled base now carries must not also be served from KV',
  );
  assert.match(block, /StillProvisional\.docx/, 'one the sync has not reached yet must still answer');
});

test('a hand-written knowledge entry is never mistaken for a superseded upload', async () => {
  // The filter keys on sourcePath, which only an upload has. An entry an admin
  // typed must survive regardless of what the compiled base contains.
  const { storage } = setup();
  await storage.saveKnowledge(
    {
      section: 'Typed by hand',
      content: 'DevSemantic is the agentic SRE plane, and this sentence was typed by a person who knows.',
      status: 'approved',
    },
    'boss@vikat.ai',
  );

  const block = await retrieve('DevSemantic agentic SRE plane', { storage });
  assert.match(block, /typed by a person/);
});
